### ISSUE TITLE
TIMEOUT_MINUTES doesn't work?

### ISSUE THREAD

**Issue by Rizean** [vinfamy/LifePlay#185]
ACTION_UNIQUEID: ri_test
ACTION_NAME: Test
WHERE: PC
WHEN: 0 - 24
MINUTES: 1 - 2
TIMEOUT_MINUTES: 500
ALSO_TIMEOUT:
EFFECTS: energy +5
CONDITIONS:
MOVE_FIRST: false
SCENE_ALWAYS: ri_test_scene
ANIMATION:

I assume I'm doing something wrong?

What I really wanted to do was `timeout(500, ri_test)` in the scene but did not feel like that would work so was going to settle for action timeout but that doesn't seem to work either. I assume I'm doing something wrong as looking at other actions their timeouts seem to work.

**Comment by Rizean** [comment]
Can confirm TIMEOUT_MINUTES does not work. Tested with `Collaborate with another YouTube creator` and `Support LifePlay on Patreon :P`

**Comment by vinfamy** [comment]
It's the Esc > Settings > No Action Timeout that's enabled by default that disables this feature. Some users complained about action timeout back in 2018 I think.
For hard-coded timeout, use scene timeout instead, then use isTimingOut like LifePlay\Content\Modules\vin_Base\Scenes\misc\propose_sex_dating_home.lpscene 
or
LifePlay\Content\Modules\vin_Base\Scenes\work\ask_for_raise.lpscene
