### ISSUE TITLE
Syntax Error 4.15

### ISSUE THREAD

**Issue by Rizean** [vinfamy/LifePlay#201]
If you see ... that means I'm only showing the part of the code line that has the issue.

LifePlay/Content/Modules/vin_Base/Scenes/home/call_a_hooker.lpscene
Line 60 `Else 1` > `Elseif 1`

LifePlay/Content/Modules/vin_Base/Scenes/business/cms_employee_having_sex.lpscene
Line 23 `Elseif` > `Elseif 1`

LifePlay/Content/Modules/vin_Incest/Scenes/cms_masterbate_caught.lpscene
Line 21 `If Actor.hadSex() || Random(10, 50) Actor:incest` > `If Actor.hadSex() || Random(10, 50) > Actor:incest`

LifePlay/Content/Modules/vin_Base/Scenes/companion/goodbye_companion.lpscene
Line 208 `Else 1` > `Elseif 1`
Line 229 `Else 1` > `Elseif 1`

LifePlay/Content/Modules/vin_Base/Interactions/leading_to_scenes/propose_sex_dating.lpscene
Line 44 `Else 1` > `Elseif 1`

LifePlay/Content/Modules/vin_NonConsensual/Scenes/prison_ag_rape.lpscene
Line 20 `"What should do with <Actor.him_or_her>` > `"What should do with <Actor.him_or_her>"`

LifePlay/Content/Modules/vin_NonConsensual/Scenes/prison_ag_rape.lpscene
Line 44 `Else 1` > `Elseif 1`

LifePlay/Content/Modules/vin_NonConsensual/Scenes/prison_ag_rape.lpscene
Line 78 missing closing "

LifePlay/Content/Modules/vin_Base/Scenes/crime/strip_search_cms.lpscene
Line 27 missing opening "

LifePlay/Content/Modules/vin_NonConsensual/Scenes/wi_ex_rape_family.lpscene
Line 47 `Else` > `Elseif 1`
Line 54 `Else` > `Elseif 2`

LifePlay/Content/Modules/vin_NonConsensual/Scenes/wi_ex_rape_ntr.lpscene
Line 47 `Else` > `Elseif 1`
Line 54 `Else` > `Elseif 2`

LifePlay/Content/Modules/vin_Base/Scenes/work/sexual_harassment.lpscene
Line 54 `peversion += Random(0, 0.5)` > `perversion += Random(0, 0.5)`

LifePlay/Content/Modules/vin_Base/virginity/npc_deflowered_by_player.lpscene
Line 23 `Actor::attractiontoplayer += 50` > `Actor:attractiontoplayer += 50`

LifePlay/Content/Modules/vin_Base/virginity/player_deflowered.lpscene
Line 25 `Actor::attractiontoplayer += 50` > `Actor:attractiontoplayer += 50`

LifePlay/Content/Modules/vin_Base/Scenes/misc/soldier_july2_cms.lpscene
Line 28 `Actor::rapportwithplayer -= 5` > `Actor:rapportwithplayer -= 5`

LifePlay/Content/Modules/vin_Pregnancy/Scenes/NPC_discovers_pregnancy.lpscene
Looks like there is a copy and paste error on lines 35-37

LifePlay/Content/Modules/vin_Incest/Scenes/incest_virgin_offered.lpscene
line 4
from: `Actor = getRelative(); If Actor.isInterestedIn(Player) && Player.isInterestedIn(Actor) && Actor.isVirgin() & Actor:rapportwithplayer > 70`
to: `Actor = getRelative(); If Actor.isInterestedIn(Player) && Player.isInterestedIn(Actor) && Actor.isVirgin() && Actor:rapportwithplayer > 70`

LifePlay/Content/Modules/vin_Base/Interactions/leading_to_scenes/get_introduced_to_john.lpscene
Lines 23 to 25 should be something like
```
        Dice = Random(300, 400)
        Price = Dice.convertToLocalCurrency(true)
        money => money + Price
```

LifePlay/Content/Modules/vin_Base/Interactions/leading_to_scenes/invite_home.lpscene
63 `If Dating` > `If Actor.isDating()`

LifePlay/Content/Modules/vin_Base/Scenes/uni_lecturer/crush_student.lpscene
LifePlay/Content/Modules/vin_Base/Scenes/uni_lecturer/student_crush.lpscene
LifePlay/Content/Modules/vin_Base/Scenes/uni_lecturer/student_sex_cms.lpscene
line 17: `If !isContactExchanged() && Actor:attractiontoplayer > 35` > `If !Actor.isContactExchanged() && Actor:attractiontoplayer > 35`

LifePlay/Content/Modules/vin_Base/Scenes/crime/prison_warden_cms.lpscene
Line 431 `If performance > 70` > `If jobperformance > 70`

LifePlay/Content/Modules/vin_Base/Interactions/leading_to_scenes/meet_new_person_i.lpscene
CompanionIntroduced is never defined. Add `CompanionIntroduced = isWithCompanion()` between line 8/9

LifePlay/Content/Modules/vin_Pregnancy/Scenes/suggest_abortion.lpscene
Incomplete code on line 24 looks like it can just be removed

LifePlay/Content/Modules/vin_Base/Interactions/leading_to_scenes/invite_home.lpscene
91 `If Dating` > `If Actor.isDating()`

I think the docs are wrong for blockNPCRelationships(Actor). See
LifePlay/Content/Modules/vin_Incest/Scenes/incest_owned.lpscene line 41
LifePlay/Content/Modules/vin_Incest/Scenes/incest_relationship.lpscene line 57

LifePlay/Content/Modules/vin_Polyamorous/scenes/poly_couple_repeats.lpscene
~~LifePlay/Content/Modules/vin_Base/Scenes/misc/male_revenge_cms.lpscene~~ See below
LifePlay/Content/Modules/vin_Netori/Scenes/bull_family.lpscene
LifePlay/Content/Modules/vin_Netori/Scenes/bull_fraternity.lpscene
LifePlay/Content/Modules/vin_Netori/Scenes/bull_friend.lpscene
LifePlay/Content/Modules/vin_Netori/Scenes/family_argues_dating.lpscene
LifePlay/Content/Modules/vin_Netori/Scenes/family_breakup_revenge.lpscene
LifePlay/Content/Modules/vin_Netori/Scenes/landlord_argues_spouse.lpscene
LifePlay/Content/Modules/vin_Netori/Scenes/neighbour_argues_dating.lpscene
LifePlay/Content/Modules/vin_Netori/Scenes/neighbour_breakup_revenge.lpscene
LifePlay/Content/Modules/vin_Polyamorous/scenes/poly_couple.lpscene
LifePlay/Content/Modules/vin_Pregnancy/Scenes/impregnation_revenged.lpscene
LifePlay/Content/Modules/vin_Pregnancy/Scenes/lesbian_sperm_donor.lpscene
line 4 `Actor = ...` >`Actor0 = ...`

LifePlay/Content/Modules/vin_Pregnancy/Scenes/pregnancy_arousal.lpscene
Line 22 `Actors.show()` > `Actor.show()`

LifePlay/Content/Modules/vin_Base/Scenes/home/call_a_hooker.lpscene
line 37 `Actor2 = getRandom()` > `Actor2 = getPerson()`

LifePlay/Content/Modules/vin_Base/Scenes/home/caught_masturbating.lpscene
line 7 `Peeping = getRandom()` > `Peeping = getPerson()`

LifePlay/Content/Modules/vin_Base/Scenes/medical/night_shift_cms.lpscene
LifePlay/Content/Modules/vin_NTR/scenes/dating_cheating_family_cms.lpscene
LifePlay/Content/Modules/vin_NTR/scenes/dating_cheating_family_shower_cms.lpscene
Line 4 `... Player.isInterested(Actor) ...` > `... Player.isInterestedIn(Actor) ...`

LifePlay/Content/Modules/vin_Base/Scenes/misc/male_revenge_cms.lpscene
Had to make some assumptions on this one.
Line 4
from: `WHO: Actor = getRelatedPeople(Dating); If Actor0.isMale() && !Actor1.isMale() && Actor1:perversion > 70 && [Actor0:rapportwithplayer > 30 || Actor0.hadSex()] && !Actor0.isDating()`
to: `WHO: Actor0 = getPerson(true); Actor1 = Actor0.getRelatedPerson(Dating); If Actor0.isMale() && !Actor1.isMale() && Actor1:perversion > 70 && [Actor0:rapportwithplayer > 30 || Actor0.hadSex()] && !Actor0.isDating()`

LifePlay/Content/Modules/vin_Base/Scenes/work/job_interview.lpscene
Invalid mood line 213
`Player(Concerned):: "I'm afraid I'm busy tonight. Maybe next time ..."`

LifePlay/Content/Modules/vin_Base/Scenes/fantasy/orcs_deflower.lpscene
Line 83 `Actor.hide()` > `Actor2.hide()`

LifePlay/Content/Modules/vin_Base/Scenes/misc/set_up_blind_date.lpscene
line 35 `... Actor1:perversion` > `... Actor:perversion`

LifePlay/Content/Modules/vin_Base/Scenes/sexwork/john_online_pimp.lpscene
Line 34 `Actor3:perversion += 0.25` > `Actor2:perversion += 0.25`

LifePlay/Content/Modules/vin_Base/Scenes/uni_tutor/tutor_cms.lpscene
line 23 `Actor2:perversion > 50 + Actor:perversion > 50` > `Actor2:perversion > 50 && Actor:perversion > 50`

LifePlay/Content/Modules/vin_Base/Scenes/work/intern.lpscene
line 40 `Intern:attractiontoplayer += Random(0, 30)*New_Person:masochist/100` > `Intern:attractiontoplayer += Random(0, 30) * [Intern:masochist / 100]`

LifePlay/Content/Modules/vin_Netori/Scenes/boss_spouse_cms.lpscene
Line 4 `... Actor1 = Actor.getRelatedPerson(Spouses) ...` > `... Actor1 = Actor0.getRelatedPerson(Spouses) ...`

LifePlay/Content/Modules/vin_NonConsensual/Scenes/wi_homeinvader_rape_neighbour.lpscene
Line 4 `WHO: Actor2 = getSpecific(Neighbour); If Random(60, 500) < Actor:attractiveness && Actor:intelligence < Random(0, 100)*Random(0, 1)` > `WHO: Actor2 = getSpecific(Neighbour); If Random(60, 500) < Actor2:attractiveness && Actor2:intelligence < Random(0, 100)*Random(0, 1)`

LifePlay/Content/Modules/vin_Pregnancy/Scenes/adoption.lpscene
line 17 `If Actor2.isValid()` > `If isPlayerMarried() && CurrentCompanion.isValid()`
line 18 `addNpcRelationship(ParentChild, Actor2, Actor)` > `addNpcRelationship(ParentChild, CurrentCompanion, Actor)`

LifePlay/Content/Modules/vin_Pregnancy/Scenes/end_pregnancy.lpscene
line 9 `"Force-ending <Actor.name>'s pregnancy ..."` > `"Force-ending <currentCompanion.name>'s pregnancy ..."`
line 10 `Actor.endPregnancy()` > `currentCompanion.endPregnancy()`

LifePlay/Content/Modules/vin_Base/Scenes/consequences/cuck_finds_out.lpscene
Guessing a bit on this one so double-check, please.
Line 9 `If IsModEnabled(vin_Netori) && [Cuck || Actor:masochist > 25]` > `If IsModEnabled(vin_Netori) && [Cuck > 0 || Actor:masochist > 25]`

LifePlay/Content/Modules/vin_Base/Scenes/family/child_sexual.lpscene
Line 4 `... Actor:age > 18` > `... Dating:age > 18`

LifePlay/Content/Modules/vin_Netori/Scenes/bull_employee.lpscene
Not sure on this one
Line 21 `If Cuck || Random(0, 50) < Actor:masochist` > `If Cuck > 0 || Random(0, 50) < Actor:masochist`

LifePlay/Content/Modules/vin_Netori/Scenes/bull_family.lpscene
LifePlay/Content/Modules/vin_Netori/Scenes/family_argues_dating.lpscene
LifePlay/Content/Modules/vin_Netori/Scenes/family_breakup_revenge.lpscene
Line 4 `Actor = getRelatedPeople(Spouses, Dating); ...`  > `Actor0 = getRelatedPeople(Spouses, Dating); ...`

LifePlay/Content/Modules/vin_Base/Quests/sabotage/scenes/sabotage_prostitute.lpscene
Not entirely sure on this one.
Line 54 `relation += 0.3*(Current:masochist - 50) ` > `relation += 0.3*(CurrentCompanion:masochist - 50)`

LifePlay/Content/Modules/vin_Base/Scenes/family/family_house_party.lpscene
Looks like a copy-paste error but not entirely sure. The player is hosting by default based on the scene. Additionally, PlayerHosting is undefined.  I believe the below is a valid fix but should double-check.
replace line 218 `0:: IsModEnabled(vin_VanillaPorn) :: "Have sex right here"`
replace line 219 `1:: "Stop it there"`
remove line 220

**Comment by vinfamy** [comment]
All done, thank you for your great help, also:
Actor = getRelatedPeople(xyz) won't set Actor but will set a bunch of variables with suffices Actor0, Actor1, ..., ActorN

**Comment by Rizean** [comment]
good to know
