### ISSUE TITLE
Grammar 4.15 - Round 1

### ISSUE THREAD

**Issue by Rizean** [vinfamy/LifePlay#203]
There are around 3K with a lot of false positives due to the nature of the game. So going to do these in batches over a few months for my sanity and yours ;)

LifePlay/Content/Modules/vin_Base/Descriptions/1.lpdesc
56: speeded > speed
464: spoonfitting > spooning
473: hilted > ?

LifePlay/Content/Modules/vin_Pregnancy/Scenes/adoption.lpscene
14: appplication > application

LifePlay/Content/Modules/vin_NonConsensual/Scenes/ag_spiked_rape.lpscene
66 occured > occurred
100 oblidge > oblige

LifePlay/Content/Modules/vin_Base/Scenes/sexwork/assaulted_by_costar.lpscene
LifePlay/Content/Modules/vin_Base/Scenes/sexwork/assaulted_by_john.lpscene
LifePlay/Content/Modules/vin_Base/Scenes/sexwork/assaulted_by_pimp.lpscene
24 alnight > all night

LifePlay/Content/Modules/vin_Base/Stats/Relationship/attractiontoplayer.lpstat
2 activites > activities

Should do a mass find/replace on defilled > defiled
LifePlay/Content/Modules/vin_Bestiality/Scenes/bestiality_cheater_cuckold_impregnate.lpscene
30 defilled > defiled

LifePlay/Content/Modules/vin_Base/Scenes/business/bargain.lpstat
2 relavant > relevant

LifePlay/Content/Modules/vin_Bestiality/Scenes/bestiality_cuckold_impregnate.lpscene
60 fulfiling > fulfilling
64 digusting > disgusting

Should do a mass find/replace on winded > wound
LifePlay/Content/Modules/vin_Bestiality/Scenes/bestiality_swinger_party.lpscene
225 winded > wound

Embarrassed vs Embarassed
Embarrassed with two r's is the correct spelling. I checked to see if maybe this was a British spelling thing and it doesn't seem to be. I'm not going to list all of the occurrences of this as there are around 130 of these. Below are two examples. A mass case-sensitive find and replace would be the easiest way to fix this. I have tested this without issue.

LifePlay/Content/Modules/vin_NonConsensual/Scenes/ag_datingfriend_rape.lpscene
52: `Player(Embarassed)` > `Player(Embarrassed)`

LifePlay/Content/Modules/vin_Base/Scenes/work/afterwork_drinks.lpscene
174: embarassed > embarrassed
191: Embarassed > Embarrassed

With the mass find/replaces and updating the projects dictionary grammar errors went from over 3k to 1448. Will do more in a day or so.

**Comment by vinfamy** [comment]
All done, thank you for your help! :)
