### ISSUE TITLE
Calling SexNoAffair(Player, Actor) where Actor is invalid will crash the game

### ISSUE THREAD

**Issue by Rizean** [vinfamy/LifePlay#208]
Calling SexNoAffair(Player, Actor) where Actor is invalid will crash the game. Haven't tested Sex(...) but would assume the same.

See LifePlay/Content/Modules/vin_NonConsensual/Scenes/ag_spiked_rape.lpscene on line 123 the Actor is not valid when the scene is forced triggered.

Could you make SexNoAffair/Sex print a message when one of the actors is invalid? ie Something to the effect of "Please report <fullPathToScene> called SexNoAffair/Sex with an invalid actor."?

**Comment by vinfamy** [comment]
noted

**Comment by vinfamy** [comment]
added isValid() checks, now in the worst case scenario, it will remove invalid actors and trigger a sex scene with the remaining valid actors, SexNoAffair(Player, Actor)  will turn into a solo scene if Actor is invalid
