### ISSUE TITLE
Crashing Bug

### ISSUE THREAD

**Issue by Rizean** [vinfamy/LifePlay#217]
"Found '<temp.name>' <-- this should not be empty"

**Comment by vinfamy** [comment]
what do you mean? Is that the what it tells you when it crashes? During which part of gameplay does this crash happen? How often?

**Comment by Rizean** [comment]
It seems like having <-- in narrative crashes the game. Sorry if I was unclear.

**Comment by Rizean** [comment]
This crashes the game

```
WHAT: 
WHERE: 
WHEN: 0 - 24
WHO: none
OTHER:

sceneStart()
  "<"
sceneEnd()
```

**Comment by vinfamy** [comment]
done, indefinite while loop caused by < without the >, added an extra safety check
