### ISSUE TITLE
Undressing in sex scenes

### ISSUE THREAD

**Issue by DRSSX4756** [vinfamy/LifePlay#55]
It would be good to have an action available in sex scenes that undresses an actor entirely. While I'm all up for partially undressed sex, if you do want to undress an actor entirely, it's quite a few clicks.

Also, even if my char has no underwear equipped, some will get equipped when her top/bottom clothing is removed. Takes away a little of the sexiness of going commando :)

**Comment by vinfamy** [comment]
Added an option to strip all with one click. Couldn't really replicate the second issue though. Are you sure the actor wasn't actually wearing underwear that's simply hidden under their clothes (to avoid clipping, there's an option in Esc > Settings to show underwear at all time)

**Comment by DRSSX4756** [comment]
Well, now that I try to recreate it, I don't see it either. Could've sworn...
