### ISSUE TITLE
timeout a specific actor

### ISSUE THREAD

**Issue by DRSSX4756** [vinfamy/LifePlay#59]
It would be cool to be able to specify an actor for a timeout or timeoutPrecise command at the end of a scene, who would then not be selected by the WHO condition. Atm I'm running an early game - my char doesn't know too many people yet - and the same guy keeps calling her to hang out several times a day. She already blew you off three times today, dude, take a hint. 

While I could reduce the scene's frequency in general, by increasing the time-out and adding some more conditions on top, I'd like to be able to keep the general frequency, and just put that guy in the fridge a while.

**Comment by vinfamy** [comment]
Done, will be available with the next version released this weekend:
- timeoutActor(hours, actor1, actor2, ..., actorN)
- timeoutActorPrecise(hours, actor1, actor2, ..., actorN)
